[package]
name = "virtualboy-gui"
version = "0.1.0"
authors = ["tompko <tompko@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.33.0"
minifb = "0.16"
wfd = "0.1.3"
wisegui = { git = "https://github.com/yupferris/wisegui" }
virtualboy-core = { path= "../virtualboy-core" }