[package]
name = "virtualboy-gui"
version = "0.1.0"
authors = ["tompko <tompko@gmail.com>"]
edition = "2018"


[dependencies]
minifb = "0.16"
wisegui = { git = "https://github.com/yupferris/wisegui" }